# ALTER TABLE `20190822db`.`users`
# DROP COLUMN `id`,
# DROP PRIMARY KEY;
# ;

# ORDER ALPHABETICALLY
# SELECT * FROM table_name ORDER BY col_name;

# DROP COL
# ALTER TABLE table_name DROP COLUMN col_name;

# REBUILD ID PK
# ALTER TABLE users ADD id int UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
